CREATE TABLE product_photos (
    id SERIAL PRIMARY KEY,
    product_id INT REFERENCES products(id) ON DELETE CASCADE,
    photo_url TEXT NOT NULL
);

INSERT INTO product_photos (product_id, photo_url)
VALUES (1, 'Artek 66 Chair 1.avif'),
       (1, 'Artek 66 Chair 2.avif'),
       (1, 'Artek 66 Chair 3.avif'),
       (1, 'Artek 66 Chair 4.avif'),
       (2, 'Borg armchair 4.avif'),
       (2, 'Borg armchair 2.avif'),
       (2, 'Borg armchair 3.avif'),
       (2, 'Borg armchair 1.avif'),
       (3, 'Hammock 5.avif'),   
       (3, 'Hammock 2.avif'),
       (3, 'Hammock 3.avif'),
       (3, 'Hammock 4.avif'),
       (3, 'Hammock 1.avif'),
       (4, 'Rocking Chair 4.avif'),
       (4, 'Rocking Chair 2.avif'),
       (4, 'Rocking Chair 3.avif'),
       (4, 'Rocking Chair 1.avif'),
       (5, 'Clas Ohlson lamp 5.avif'),
       (5, 'Clas Ohlson lamp 2.avif'),
       (5, 'Clas Ohlson lamp 3.avif'),
       (5, 'Clas Ohlson lamp 4.avif'),
       (5, 'Clas Ohlson lamp 1.avif'),
       (6, 'Coffee Table 5.avif'),
       (6, 'Coffee Table 2.avif'),
       (6, 'Coffee Table 3.avif'),
       (6, 'Coffee Table 4.avif'),
       (6, 'Coffee Table 1.avif'),
       (7, 'Table Lamp 2.avif'),
       (7, 'Table Lamp 3.avif'),
       (7, 'Table Lamp 4.avif'),
       (7, 'Table Lamp 5.avif'),
       (7, 'Table Lamp 1.avif'),
       (8, 'Sheep Stool 3.avif'),
       (8, 'Sheep Stool 4.avif'),
       (8, 'Sheep Stool 5.avif'),
       (8, 'Sheep Stool 1.avif'),
       (8, 'Sheep Stool 2.avif'),
       (9, 'Occasional table 2.avif'),
       (9, 'Occasional table 3.avif'),
       (9, 'Occasional table 4.avif'),
       (9, 'Occasional table 5.avif'),
       (9, 'Occasional table 1.avif'),
       (10, 'Handmade Bedside Table 4.avif'),
       (10, 'Handmade Bedside Table 3.avif'),
       (10, 'Handmade Bedside Table 5.avif');
 
 
